### ISSUE TITLE
addParticule (unique anim without loadings others from the SpriterEntity obj)

### ISSUE THREAD

**Issue by 2smacks** [loudoweb/SpriterHaxeEngine#12]
I use Spriter only for particules in my game, so in my SCML file, I have juste one entity with all the particules animations.

When I add an particule to the game (new Spriter obj to the SpriterEngine obj), I suppose creating a particule (new Spriter obj) copy all the SCML animations just for using one of them.

What do you think of the possibility to create a light particule Spriter obj with a unique specified animation (with autoDestroy boolean parameter) ?

Maybe like that :

function addParticule(_entity:String, _animation:String, _autoDestroy:Bool):Spriter
{}

**Comment by loudoweb** [comment]
I had left this issue because of 

> When I add an particule to the game (new Spriter obj to the SpriterEngine obj), I suppose creating a particule (new Spriter obj) copy all the SCML animations just for using one of them.

But now the SCML is not copied anymore in each Spriter so you can have many Spriters using the same SCML. I close the issue.
