### ISSUE TITLE
FlixelLibrary.hx - Type not found : flixel.graphics.frames.FlxAtlasFrames

### ISSUE THREAD

**Issue by diegomachado** [loudoweb/SpriterHaxeEngine#25]
Got this error due to HaxeFlixel's updated structure:

``
/usr/lib/haxelib/SpriterHaxeEngine/1,6,0/spriter/library/FlixelLibrary.hx:4: characters 7-44 : Type not found : flixel.graphics.frames.FlxAtlasFrames
``

FlxAtlasFrames does not exist anymore.

**Comment by diegomachado** [comment]
Allright, just checked with @Beeblerox that this plugin relies on HaxeFlixel's dev branch.

**Comment by SadaleNet** [comment]
For anyone who want to use flixel with stable version of Haxe, @Beeblerox had written a version of FlixelLibrary that works with stable version! [Here](https://github.com/loudoweb/SpriterHaxeEngine/blob/faef546ea09d9eb9753dcc2afc8c9f4261424fb6/spriter/library/FlixelLibrary.hx) is the file.
