### ISSUE TITLE
Animation of Subentities aren't played

### ISSUE THREAD

**Issue by SadaleNet** [loudoweb/SpriterHaxeEngine#28]
Reference file for reproducing the bug is available [here](http://secret.sadale.duckdns.org/misc/subentitiesAnimationBug/scml.tar.gz)

Expected output of `engine.getEntity('test').playAnimFromEntity('scene', 'MoveAnimation')` (Due to technical issue, the gif below is playing slower than it should):

![](http://secret.sadale.duckdns.org/misc/subentitiesAnimationBug/expected.gif)

However, the runtime cannot animate the subentities. Here is the [actual output](http://secret.sadale.duckdns.org/misc/subentitiesAnimationBug/actual.webm)

Notice that the blue balls don't rotate as it should.

**Comment by SadaleNet** [comment]
I've got some rough idea on the cause of this bug. It seems that the issue is that there is no inbetween animation of keyframes in subentities in this runtime. With the use of reference file way above, in https://github.com/loudoweb/SpriterHaxeEngine/blob/fe606b9d21f7e0214c1b9d32723bb2df7a17c849/spriter/definitions/SpriterAnimation.hx#L179 , the `currentSubKey.t` is either `0` or `1`. In our animation, the graphic for `t="0"` and `t="1"` are identical. Therefore, it looks like that there is no animation in subentities.

I've made the observation above by changing part of the scml file from this:

```
            <timeline id="0" name="base" object_type="entity">
                <key id="0" spin="0">
                    <object entity="0" animation="1" t="0" x="338.217391" y="-173.956522" angle="0"/>
                </key>
                <key id="1" time="500" spin="0">
                    <object entity="0" animation="1" t="1" x="77.347826" y="-164.173913" angle="0"/>
                </key>
            </timeline>
```

to this:

```
            <timeline id="0" name="base" object_type="entity">
                <key id="0" spin="0">
                    <object entity="0" animation="1" t="0" x="338.217391" y="-173.956522" angle="0"/>
                </key>
                <key id="1" time="500" spin="0">
                    <object entity="0" animation="1" t="0.5" x="77.347826" y="-164.173913" angle="0"/>
                </key>
            </timeline>
```

**Comment by loudoweb** [comment]
thanks for your comment. Can you tell me what version are you using (haxelib, master or dev branch)

**Comment by SadaleNet** [comment]
haxelib

**Comment by SadaleNet** [comment]
My proposal fix for this bug: https://github.com/SadaleNet/SpriterHaxeEngine/commit/cb2ee9d94eda72420e9c776348f80a9ba7a35aee

I've very briefly tested it. It seems to be working.

Main issues of this fix:
* Not thoroughly tested
* Code duplication with keyFromRef()
* More issues yet to be found :P

You may want make adaption from this fix.

**Comment by SadaleNet** [comment]
Did some further testing. The patch seems to be working. I'll leave this issue here for now.

What I did in further testing:

* Check whether interpolation works correctly
* Check whether sub-sub-entities work

Of course, there is no harm to do even further testing. I'm very new to Haxeflixel and Spriter(like started using it yesterday). I don't bother sending a pull request for now because this project may have some coding conventions that I didn't know, and my patch may have bugs. :P

**Comment by SadaleNet** [comment]
Found a bug in the patch. The patch assumes linear animation for subentities. It should consider the interpolation method specified by the editor.

**Comment by SadaleNet** [comment]
[New patch that fix the interpolation problem](https://github.com/loudoweb/SpriterHaxeEngine/compare/master...SadaleNet:master?diff=unified&name=master#diff-4523e00509e5e93bf784fa2820381480).

[A file that proves the new patch fixes the interpolation problem](http://secret.sadale.duckdns.org/misc/subentitiesAnimationBug/scml.tar.gz)

While I was testing around, I found another bug. See #29 .

**Comment by loudoweb** [comment]
Hey @SadaleNet ! Thank you very much for helping improving the framework. I'll check your code as soon as I can.

**Comment by loudoweb** [comment]
I figured out how to fix this in a cleaner way.
I've commited in the dev branch.

```haxe
//in SubEntityTimelineKey.hx
override public function linearKey(keyB:TimelineKey, t:Float):Void
 {
        super.linearKey(keyB, t);
 	var keyBSub:SubEntityTimelineKey = cast keyB;
 	this.t = linear (this.t, keyBSub.t, t); 
 }
```

Thanks again for this bug report. I will put the v2 (dev branch) in haxelib soon.
