### ISSUE TITLE
Cannot get the points of an entity

### ISSUE THREAD

**Issue by Tembac** [loudoweb/SpriterHaxeEngine#30]
I'm using this code to get the spriter:

                headSpriter = PlayState.instance.engine.addSpriter("head",X,Y);
		headSpriter.info.x = FlxG.width *0.75;
		headSpriter.info.y = -FlxG.height * 0.75;

To play:

		headSpriter.playAnimFromEntity("cabeza", "transicionAIdleCabeza", toIdleAnim, true);

On update I want to get the list of points and place eyes over them:

		var points:Array<SpatialInfo> = headSpriter.getPoints();
		var point:SpatialInfo;
		for (i in 0...points.length)
		{
			point = points[i];
			var eye = arrayEyes[i];
			eye.setPosition( point.x,   point.y);
		}

But the eyes are not showing where they suppose to go.

**Comment by Tembac** [comment]
Noticed that it was working on the master library. The change that introduced this bug is in compute function of the abstract library at line 67. It should create a new SpatialInfo instead of using the existing one.

	public function compute(info:SpatialInfo, pivots:PivotInfo, width:Float, height:Float):SpatialInfo
	{
		var degreesUnder360 = SpriterUtil.under360(info.angle);
		var rad = SpriterUtil.toRadians(degreesUnder360);
		var s = Math.sin(rad);
		var c = Math.cos(rad);
		
		var pivotX =  info.x;
		var pivotY =  info.y;
		
		var preX = info.x - pivots.pivotX * width * info.scaleX;
		var preY = info.y + (1 - pivots.pivotY) * height * info.scaleY;	
		
		var x2 = (preX - pivotX) * c - (preY - pivotY) * s + pivotX;
        var y2 = (preX - pivotX) * s + (preY - pivotY) * c + pivotY;
		return new SpatialInfo(x2, -y2, degreesUnder360, info.scaleX, info.scaleY, info.a, info.spin);
	}

**Comment by loudoweb** [comment]
Thanks for your report. Oh I see. Sorry for this. I did that to avoid creating too much SpatialInfo and have better performance.
I think we can create new SpatialInfo only for this maybe by adding copy() to the SpatialInfo in the following line :

https://github.com/loudoweb/SpriterHaxeEngine/blob/dev/spriter/definitions/SpriterAnimation.hx#L198
```haxe
points.push(library.compute(_cachedSpatialInfo.copy(), activePivots, 0, 0));
```

Can tou try ?

**Comment by Tembac** [comment]
Yes, that also works.

Thanks for your dedication. This seems like a very complex thing to make.

**Comment by loudoweb** [comment]
I've just fix this bug in the dev branch. Thank you very much Tembac for the bug report.
