### ISSUE TITLE
Playing animations in reverse

### ISSUE THREAD

**Issue by Tembac** [loudoweb/SpriterHaxeEngine#31]
Is it possible to play an animation from finish to start?

**Comment by loudoweb** [comment]
You can play backward like that : `Spriter.playbackSpeed = -1;`

But it will start at time 0. If you need to play at the end time. Try `Spriter.timeMS = Spriter.scml.entities.get(Spriter.scml.entityName).animationsName[Spriter.scml.currentAnimation].length`

Sorry for the inconvenience. I will update Spriter with a shortcut method this afternoon to play backward from the end time :)

**Comment by Tembac** [comment]
Thanks!

**Comment by Tembac** [comment]
It works but with two problems: The animation never stops and the callback is never called. This is my code:

	```
ravenSpriter = engine.addSpriter("Raven");
		ravenSpriter.info.x = FlxG.width *0.5;
		ravenSpriter.info.y = -FlxG.height * 0.9;
	ravenSpriter.playAnim("Ani04", playNextRavenAnim);
		ravenSpriter.playbackSpeed = -1;
		ravenSpriter.timeMS = ravenSpriter.scml.entities.get(ravenSpriter.spriterName).animations.get(ravenSpriter.scml.currentAnimation).length;
```

**Comment by loudoweb** [comment]
Sorry it should be `scml.entities[scml.currentEntity].animations[scml.currentAnimation].length`

I've commited the first version of the method here:
https://github.com/loudoweb/SpriterHaxeEngine/commit/0c96d7c8b8e09f7ba8ddeef96b655bdc33341545

But I didn't see your message so I didn't test callback yet. I will update in few moments.
I think right now the callback will throw at time=length but if the anim is reversed it should throw at time=0 right ?

**Comment by loudoweb** [comment]
I wonder if you set a Spriter in reverse and then you change your anim, should this second animation play in reverse too?

**Comment by loudoweb** [comment]
I forget something with the last commit. You can use 8e4118e but b994db6 needs an update.

**Comment by loudoweb** [comment]
Hum I've still found something to fix. If you use reverse() on an non looping animation it doesn't work. I need to set timeMS=length every animation when reversed.

**Comment by loudoweb** [comment]
I think it's done now :)

**Comment by Tembac** [comment]
Thanks @loudoweb ! 

Sorry I couldn't be more attentive about your messages today but I was busy. I'll try it and tell you if I find something wrong.
