### ISSUE TITLE
Placement is off. 

### ISSUE THREAD

**Issue by troyedwardsjr** [loudoweb/SpriterHaxeEngine#36]
Placement is off. It's consistently off on all targets (Neko, HTML5, CPP) except Flash, where it's still off by a pixel but to the right instead of the left. It may not make a difference in large images, but in pixel art, being off by one pixel is a lot.

This happens on both the SpriterLibrary and the FlixelLibrary so I don't think it has anything with the library implementation. 

http://i.imgur.com/az53Euf.png
![az53euf](https://cloud.githubusercontent.com/assets/16667416/18025255/04560488-6bf2-11e6-88d1-6a7b47354ef3.png)

**Comment by loudoweb** [comment]
Thanks for reporting this issue.

Can you send me a sample SCML?

Can tou tell if the legs use integer values for the positions or float? If float values, are they closest to the floor or to the ceiling?

All openfl libraries send float values to the openfl renderer. Maybe openfl renders with rounding the values and Spriter use floor instead or something like that?
Or maybe that's a different problem but it will be great to have a sample.

**Comment by troyedwardsjr** [comment]
Sure, a simple sample with no animations:
https://mega.nz/#!70UDCKxR!uqErQvFI1-1Z8VyHJwUIJ6XLcfr3CnrZBRiokEF8S2s

What you're saying makes sense, though I just checked the editor and the scml and the x/y positions appear to be ints in the scml "x="5" y="2" and floats in the editor "5.00000", "2.00000", very precise and would presume they would be rounded correctly even if the openfl renderer makes them floats. Haven't looked deep into the lib yet.

Thanks for taking the time to address it. Appreciate your help!

**Comment by loudoweb** [comment]
At scale 1, I don't have any problem with your scml on flash and neko.
But if I set the scale to 10, I have indeed one pixel off on one leg.
So I guess it's a scale issue. I'll make further test next week.

**Comment by loudoweb** [comment]
I think it has been fixed in the last Spriter r9.
