### ISSUE TITLE
Cache SCML's to binary to save loading time (if that's possible)

### ISSUE THREAD

**Issue by sruloart** [loudoweb/SpriterHaxeEngine#5]
Like this Bardbarian's guys trick (later in the thread): http://forum.starling-framework.org/topic/json-or-xml: "what we did with Bardbarian: With over 30 SCML files to load, it was starting to get really slow. So we just added some code to our startup, to cache them all in a binary file.
Just make a big hash of all your StarlingAnimation instances, then use writeObject to store in a bytearray, and save to a little file "animations.bin".
When on the device, load the bin file, and extract each animation. Load times go from like 3000ms, to 10ms [:D]

WRITE:
var f:File = AirUtils.projectFolder.resolvePath("src/assets/spriter/scmlCache.bin");
var ba:ByteArray = new ByteArray();
ba.writeObject({sd: animationsByName, hd: animationsByNameHd});
ba.compress();

var fs:FileStream = new FileStream();
fs.open(f, FileMode.WRITE);
fs.writeBytes(ba, 0, ba.bytesAvailable);
fs.close();

READ:
var ba:ByteArray = new ByteArray();
var stream:FileStream = new FileStream();
stream.open(cacheFile, FileMode.READ);
stream.readBytes(ba, 0, stream.bytesAvailable);
stream.close();
ba.uncompress();
animationsByName = scale == 1? ba.readObject().hd : ba.readObject().sd; "

**Comment by loudoweb** [comment]
@sruloart sorry for the long wait, for now it's on the dev branch. Tell me what do you think about it.

**Comment by sruloart** [comment]
:+1: exactly what I've meant! I the performance benefit should get even higher the more .scmls you're going to have in your game.

**Comment by loudoweb** [comment]
Just need a feature to handle more scml in SpriterEngine now :D
